spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        #关闭健康性检查
        health.enabled: false
        native:
          uri: classpath:repos/config
          searchPaths: 'common,{application}'
          cloneOnStart: true
          repos:
            user:
              pattern: user-*
              cloneOnStart: true
              uri: classpath:repos/user/config
              searchPaths: 'common,{application}'
            oauth:
              pattern: oauth-*
              cloneOnStart: true
              uri: classpath:repos/oauth/config
              searchPaths: 'common,{application}'
            efence:
              pattern: efence-*
              cloneOnStart: true
              uri: classpath:repos/efence/config
              searchPaths: 'common,{application}'
    consul:
      discovery:
        prefer-ip-address: true
        tags: api

#配置加密
#encrypt:
#  keyStore:
#    location: classpath:/server.jks
#    password: configsecret2
#    alias: configkey
#    secret: configsecret

