spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    separator: //

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG
    com.wudimanong.oauth.resource.dao.mapper: DEBUG
